# Generated by Django 5.2 on 2025-05-02 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_date_to_apply", models.DateTimeField(blank=True, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("job_type", models.CharField(blank=True, max_length=100, null=True)),
                ("salary", models.CharField(blank=True, max_length=100, null=True)),
                ("eligibility", models.TextField(blank=True, null=True)),
                ("apply_link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
